version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: ["./scripts/wait-for-it.sh", "db:5432", "--", "yarn", "start-dev"]
  db:
    image: mysql:8.0.12
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: wotb-grinder
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
volumes:
  db_data: {}
