import { DataTypes } from 'sequelize';
import { sequelize } from '../config';

const PlayerStatisticsAll = sequelize.define('PlayerStatisticsAll', {
  accountId: { type: DataTypes.STRING, allowNull: false },
  avgDamageAssisted: { type: DataTypes.FLOAT },
  avgDamageAssistedRadio: { type: DataTypes.FLOAT },
  avgDamageAssistedTrack: { type: DataTypes.FLOAT },
  avgDamageBlocked: { type: DataTypes.FLOAT },
  battleAvgXp: { type: DataTypes.INTEGER },
  battles: { type: DataTypes.INTEGER },
  battlesOnStunningVehicles: { type: DataTypes.INTEGER },
  capturePoints: { type: DataTypes.INTEGER },
  damageDealt: { type: DataTypes.INTEGER },
  damageReceived: { type: DataTypes.INTEGER },
  directHitsReceived: { type: DataTypes.INTEGER },
  draws: { type: DataTypes.INTEGER },
  droppedCapturePoints: { type: DataTypes.INTEGER },
  explosionHits: { type: DataTypes.INTEGER },
  explosionHitsReceived: { type: DataTypes.INTEGER },
  frags: { type: DataTypes.INTEGER },
  hits: { type: DataTypes.INTEGER },
  hitsPercents: { type: DataTypes.INTEGER },
  losses: { type: DataTypes.INTEGER },
  maxDamage: { type: DataTypes.INTEGER },
  maxDamageTankId: { type: DataTypes.INTEGER },
  maxFrags: { type: DataTypes.INTEGER },
  maxFragsTankId: { type: DataTypes.INTEGER },
  maxXp: { type: DataTypes.INTEGER },
  maxXpTankId: { type: DataTypes.INTEGER },
  noDamageDirectHitsReceived: { type: DataTypes.INTEGER },
  piercings: { type: DataTypes.INTEGER },
  piercingsReceived: { type: DataTypes.INTEGER },
  shots: { type: DataTypes.INTEGER },
  spotted: { type: DataTypes.INTEGER },
  stunAssistedDamage: { type: DataTypes.INTEGER },
  stunNumber: { type: DataTypes.INTEGER },
  survivedBattles: { type: DataTypes.INTEGER },
  tankingFactor: { type: DataTypes.FLOAT },
  wins: { type: DataTypes.INTEGER },
  xp: { type: DataTypes.INTEGER },
});

export default PlayerStatisticsAll;
